### ISSUE TITLE
Release for .NET 4.6

### ISSUE THREAD

**Issue by fefno** [danikf/tik4net#10]
Could you please build a release for .net 4.6?

**Comment by danikf** [comment]
Why not :-) 
Project has been switched to 4.6.1 .NET (default) in 2.1.0.0 version. Versions for 3.5, 4.0, 4.5 and 4.6 are available via sources and nuget. Binaries will be published as soon as guys from mikrotik will fix the file upload in their phorum.

Enjoy,
D
