### ISSUE TITLE
Not work on ASP MVC5

### ISSUE THREAD

**Issue by ngocthua92** [danikf/tik4net#11]
It show that 'The type or namespace name 'tik4net' could not be found (are you missing a using directive or an assembly reference?)
Please help me. I use nuget package

**Comment by danikf** [comment]
Hi,

please ensure:
1) The project witch is using tik4net has reference to the package
2) You have "using tik4net;" statement in yout *.cs code
3) You are referencing version of tik4net according .NET version which is used in your project (support for .NET 4.6 has been added in 2.1.0.0 tik4net version)

Basically - it should work :-)

D

**Comment by anishpsla** [comment]
I think he is referring to ASP.NET core with .net core 1.0. I also interested in .net core support. It will help us to create Mikrotik based application in Linux using C#

**Comment by danikf** [comment]
Hi,
I have this support in internal roadmap, but there is problem with multi-net release. I will wait for studio msbuild support for .net core (planned 03/2017).

D

**Comment by angelcalvasp** [comment]
Any updates on .net core support?

**Comment by dansiegel** [comment]
@danikf I've already ported this to NetStandard, I know you mentioned something about mutli-net release... what specifically are you looking to support? I'm happy to submit a PR for you.

**Comment by danikf** [comment]
Hi,

multi-net release means, that you could compile version for all .NETs from one source (and from identical csprojs, which is the problem). 

Please - could you contact me directly (via PM in support forum?) to discuss it?

Thanks,
D

**Comment by dansiegel** [comment]
@danikf I'm very familiar with cross compiling libraries, I was just asking what versions you were looking to support. I tried to contact you in the support forum but where it says "Contact danikf" it's just text with no link.

**Comment by invertedtomato** [comment]
We needed .NET standard support, better thread-safety and a few other things. The basic architecture was making it a tough gig to work with though. I've forked the project and made some fairly hefty changes to make this possible and meet our needs. 

https://github.com/invertedtomato/tiklink

@danikf I figured it would make an insulting pull-request and have instead rebranded the project. Let me know if you'd be interested in merging!

**Comment by danikf** [comment]
Hi - thank you for your work. I have just commited updated version with .NET core support (backward compatible]. I will take a look on your changes.

BTW - as for thread safety - i can not imaginate any reason for multithread connection - why you just dont use more connections?

Have a nice day,
D

**Comment by invertedtomato** [comment]
Sure, we could use multiple connections, though the API protocol has support for parallel queries so we may as well make use of it! Thanks @danikf
