### ISSUE TITLE
not enough permissions (9)

### ISSUE THREAD

**Issue by udhayamoorthi** [danikf/tik4net#12]
Getting not enough permission (9) error message while executing the bellow usermanager command.

Help needed !!

```
ITikCommand activepro = connection.CreateCommand("/tool/user-manager/user/create-and-activate-profile",
            connection.CreateParameter("customer", "admin"),
            connection.CreateParameter("numbers", "udhay"),
            connection.CreateParameter("profile", "Quota5GV10d"));
            activepro = connection.CreateCommand(activate);
            var retmsg = activepro.ExecuteScalar();
           Console.WriteLine("Result: " +  retmsg);
```

Regards
Udhaya Moorthi

**Comment by danikf** [comment]
Hi,
the error is from mikrotik or from .NET runtime? Could you please post here the whole exception with stack trace?

My guess is that your mikrotik account has no permission to perform that change ...

D

**Comment by danikf** [comment]
Closing as unrepeatable ...

D
