### ISSUE TITLE
I can't remove the session using .id

### ISSUE THREAD

**Issue by romiltonfdo** [danikf/tik4net#13]
Actually we have tried to remove the session manually by using the below command. I can fetch the id using /ip/hotspot/active/print. I tried so many times it shows the error "no such item (4). Kindly help me to resolve this issue.

 ITikCommand RemoveSession = connection.CreateCommand("/ip/address/remove",
                                            connection.CreateParameter(".id", id));
                        RemoveSession.ExecuteNonQuery();

**Comment by danikf** [comment]
Hi,
it is not problem of the API, but problem of mikrotik API syntax.
See http://wiki.mikrotik.com/wiki/Manual:API for details.

The reason could be usage of different ids / id formats. API ID should look like this: *6

Your code should be like this (apologize for dirty code):
```cs
            const string IP = "192.168.1.1/24";
            const string INTERFACE = "ether1";

            //create IP
            var createCommand = Connection.CreateCommandAndParameters("/ip/address/add",
                "interface", INTERFACE,
                "address", IP);
            createCommand.ExecuteNonQuery();

            //find our IP (fast and dirty way)
            var id = Connection.CallCommandSync("/ip/address/print", $"?=address={IP}").OfType<ITikReSentence>().Single().GetResponseField(TikSpecialProperties.Id);

            //delete by ID
            var deleteCommand = Connection.CreateCommandAndParameters("/ip/address/remove",
                TikSpecialProperties.Id, id);
            deleteCommand.ExecuteNonQuery();
```
NOTE: will work only for manually added IPs!

D
