### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by SaadQais** [danikf/tik4net#15]
Hi 
I'm starting using this project for my network (ISP company) and it is so great, but now i want to create a mikrotik terminal inside my web, is that possible? and what tool should i use for that? i'm thinking to create a new script file and run it and remove it.

**Comment by danikf** [comment]
Hi,
IMHO this API would not be very usefull if you want to use console sytntax. For terminal you need both input and output sentences. There are at least two options:
1) Use this API and use api syntax (see tik4net.console project)
2) Use some telnet/ssh library to access mikrotik router

BTW - you would have to (somehow solve) some kind of session sharing - I would not recomend you to create new session for every request you calls.

D
