### ISSUE TITLE
Script source code

### ISSUE THREAD

**Issue by pmishka** [danikf/tik4net#17]
Hello!
here is a small bug when you try to get script content.
If script contains \r\n - regex doesn't work thinking that script source is multiline.
Here is my fix:
public ApiSentence(IEnumerable<string> words)
        {
            Regex keyValueRegex = new Regex("^=?(?<KEY>[^=]+)=(?<VALUE>.*)$"**, RegexOptions.Singleline**);
            foreach(string word in words)
            {
               ...
            }
        }

**Comment by danikf** [comment]
Halo,

thank you! Integrated into source code.

D

2017-03-29 16:25 GMT+02:00 pmishka <notifications@github.com>:
