### ISSUE TITLE
Added value is always 0

### ISSUE THREAD

**Issue by neoprogger** [danikf/tik4net#18]
Hi,
Whenever I try to enter a value they are 0.
Dim cmd As ITikCommand = connection.CreateCommandAndParameters("/interface/ethernet/switch/mac-based-vlan/add","src-mac-address=11:22:33:44:55:66" "new-customer-vid", "15")

Any help?

**Comment by neoprogger** [comment]
tried  2hours, 5 min after posting I found the solution...
Dim cmd As ITikCommand = connection.CreateCommandAndParameters("/interface/ethernet/switch/mac-based-vlan/add", TikCommandParameterFormat.NameValue, "src-mac-address", "11:22:33:44:55:66", "new-customer-vid", "15")

thanks anyway for this great project

**Comment by danikf** [comment]
Hi,
parameter type is calculated from command usage if you create parameters without specific parameter type. So the guess is, that you tried to execute command via some "load" overload like ExecuteSingleRow or ExecuteList. You should use ExecuteNonQuery or ExecuteScalar in this case.
BTW - with R/O mapper like API it will be much easier :-)

D
