### ISSUE TITLE
API-SSL

### ISSUE THREAD

**Issue by Deantwo** [danikf/tik4net#2]
I don't see any support for connecting to the API via SSL. There is only ```Api```, ```Ssh```, and ```Telnet``` in your project right now.
You can take this as a feature request I guess?

The manual (here: [Manual:API-SSL](http://wiki.mikrotik.com/wiki/Manual:API-SSL)) says that it is available in RouterOS 6.1 and onward. While there isn't much information on it here, from my understanding it is mostly the TCP connection that needs to be setup differently, everything else is the same. ([source](http://forum.mikrotik.com/viewtopic.php?t=91622))

Edit: Oh, just noticed it is already on your to-do list. Sorry.

**Comment by danikf** [comment]
Hi,

situation is a little bit more complicated, because it is not exactly known, which SSL algorithm is used for cipher without certificates (which is - as I believe - the typical usage).

Router always closes the connection for each available SSL configuration I tried.

D

**Comment by danikf** [comment]
api-ssl support (with certificates) added (alpha).
