### ISSUE TITLE
how filter like dynamic

### ISSUE THREAD

**Issue by gitlsl** [danikf/tik4net#20]
I use ` var list = Connection.LoadList<IpAddress>(Connection.CreateParameter("dynamic", null));` but it has not work  ,can you help me

**Comment by gitlsl** [comment]
ok ,I try `var list = Connection.LoadList<IpAddress>(Connection.CreateParameter("dynamic","yes"));` it seem work fine

**Comment by gitlsl** [comment]
on console I can use `:execute script={/interface set ADSL-2 disabled=yes;:delay 5s;/interface set ADSL-2 disabled=no;}` 
do you know how execute it in api ?

**Comment by danikf** [comment]
Hi, I think that the second sample is the only one working with mikrotik API. (you have to pass parameter value when you filtering results ...)

D
