### ISSUE TITLE
connection.Open  timeout

### ISSUE THREAD

**Issue by gitlsl** [danikf/tik4net#24]
you commit timeout at  latest code, the code is useful when socket connect ok,  but if the host can not be connected, connection.Open will never return in my test（2 minutes）

**Comment by gitlsl** [comment]
some code 
`
 var success = _tcpConnection.ConnectAsync(host, port).Wait(TimeSpan.FromSeconds(5));
     if (!success)
            {
                throw new Exception("Failed to connect.");
            }
`

**Comment by danikf** [comment]
You are right - my mistake. I will fix ASAP :-)
Thanks,
D

**Comment by danikf** [comment]
Fixed :-)

D
