### ISSUE TITLE
Example for /tool wol

### ISSUE THREAD

**Issue by hkusulja** [danikf/tik4net#25]
How to use ITikCommand with /tool wol interaface=ether1 mac=AA...

**Comment by danikf** [comment]
Hi,

it is easy to achieve by ADO like API. But I have already commit easy to use facade ToolWol (highlevel API). See  de9bb3a commit. 

```           
var command = connection.CreateCommandAndParameters("/tool/wol", TikCommandParameterFormat.NameValue, "mac", macAddress.Address);
command.ExecuteSingleRow();
```
D
