### ISSUE TITLE
How to reset-counters

### ISSUE THREAD

**Issue by RaelKbg** [danikf/tik4net#27]
Hi there 

I'm putting a tool in place that will help reset the download used in the user-manager. I'm using the query below from mikrotik's terminal and it works:
/tool user-manager user print where download-used >=1000000000;[/tool user-manager user reset-counters numbers=0] 

I'm using the tik4net to accomplish this, unfortunately my codes aren't working. please see below and advise a work around:

connection.Open(ip, user, pwd);

                string[] str = new string[4];
                str[0] = ">download-used";
                str[1] = "1000000000;";
                str[2] = "/tool/user-manager/user/reset-counters/numbers";
                str[3] = txtreset.Text;
            
                
                ITikCommand cmd = connection.CreateCommandAndParameters("/tool/user- 
                                        manager/user/print", str);

**Comment by danikf** [comment]
From another thread:

>when I'm trying to reset-counters im getting a 'no such command' error.

>Please help, this is my code:
>var cmd= connection.CreateCommandAndParameters("/tool/user-manager/user/reset-counters ", "?=numbers", txtreset.Text);

Answer:
Numbers are not supported via API. Use Ids.

May be this thread will help you: https://forum.mikrotik.com/viewtopic.php?t=43718

BTW - please use support forum and not issues to ask questions.

D

**Comment by RaelKbg** [comment]
I tried using the .id but got the same no such command error. I tested the command from the terminal, you can only reset-counters per numbers not per .id. 

I followed the logic for the php api to reset-counters that also didn't work. 

I will create another post on the forum.

**Comment by RaelKbg** [comment]
Hi danikf


I tried using .id instead of numbers but Im getting the same error "no such command". I tested the command query from the terminal and .id isnt recognised to reset-counters.


Do you have any work around? please help


thanks



________________________________
De : Daniel Frantik <notifications@github.com>
Envoyé : jeudi 12 avril 2018 09:50
À : danikf/tik4net
Cc : RaelKbg; Author
Objet : Re: [danikf/tik4net] How to reset-counters (#27)


From another thread:

when I'm trying to reset-counters im getting a 'no such command' error.

Please help, this is my code:
var cmd= connection.CreateCommandAndParameters("/tool/user-manager/user/reset-counters ", "?=numbers", txtreset.Text);

Answer:
Numbers are not supported via API. Use Ids.

May be this thread will help you: https://forum.mikrotik.com/viewtopic.php?t=43718

BTW - please use support forum and not issues to ask questions.

D

**Comment by danikf** [comment]
The command should be in this format (example is for QT but I hope you will understand it):
```
/queue/tree/reset-counters
=.id=*10009D3
```
And command should be executed with proper .id value (obtained by `/print`) and via ExecuteNonQuery (if you want to use ADO like API).

D
