### ISSUE TITLE
No tag is attached to sent commands

### ISSUE THREAD

**Issue by AsafMag** [danikf/tik4net#30]
Hello,

A tag is not attached to sent commands, which makes them take each others' responses as their own when sent in parallel.

I'm using a version of late 2017 and haven't seen a change in the latest version.

**Comment by danikf** [comment]
Hi,
do you have sample code? Sounds very unlikely tu me ...
D

**Comment by AsafMag** [comment]
```
var a = new Thread(() =>
{
    while (true)
    {
        var command = connection.CreateCommand("/system/health/print");
        command.ExecuteSingleRow();
    }
});

var b = new Thread(() =>
{
    while (true)
    {
        var command = connection.CreateCommand("/system/health/print");
        command.ExecuteSingleRow();
    }
});

a.Start();
b.Start();
```

One of them throws when you start b.
https://wiki.mikrotik.com/wiki/Manual:API#Tags

**Comment by danikf** [comment]
Could you please explain the reason for running two synchronous commands in parallel way? Tags are (of course) supported by async methods - ExecuteAsync.

Thanks,
D

**Comment by AsafMag** [comment]
Oh I see, I missed it. Is there a version with duration?

**Comment by danikf** [comment]
Well,

I have added some support for sending .tag embeded in command rows / parameters witch could be also solution (see connected commit). Just to add more intuitive interface. But ExecuteAsync (and ```ExecuteListWithDuration```) is the solution I would preffer.

D
