### ISSUE TITLE
/system/reboot

### ISSUE THREAD

**Issue by hebertonlp** [danikf/tik4net#32]
The command system reboot frozen the thread waiting for response that not exists, is possible to make a Command without a response waiter?

ex: ExecuteNonWait

**Comment by danikf** [comment]
Hi,

ExecuteNonQuery works for me. Done sentence is sent before router is rebooted. I will recommend to catch IOException around connection Dispose (connection could be closed before logout is performed - I will address it with next commit).

```
                var command = connection.CreateCommand("/system/reboot");
                command.ExecuteNonQuery();
```

D
