### ISSUE TITLE
ExecuteListWithDuration causes memory leaks

### ISSUE THREAD

**Issue by AsafMag** [danikf/tik4net#34]
I use `ExecuteListWithDuration` with a huge duration. The local variable `results` keeps all resentences and causes memory leaks. Can you add a parameter that allows dropping the results?

**Comment by danikf** [comment]
Hi,

use ```ExecuteAsync``` instead. ```ExecuteListWithDuration``` is only synchronous wrapper around it. Synchronous behavior of this method is the reason to keep all responses until method end.

D
