### ISSUE TITLE
Rx o Tx of Interface

### ISSUE THREAD

**Issue by hreynaldoh** [danikf/tik4net#37]
Goodnight

To obtain the Rx and Tx values ​​of the interface, in which way it is done, thank you in advance.

hreynaldoh

**Comment by danikf** [comment]
Hi,

please use support forum instead of opening issues.

I have just re-posted there your question and aslo the answer ...
https://forum.mikrotik.com/viewtopic.php?f=9&t=99954&p=679383#p679383
D
