### ISSUE TITLE
ExecuteListWithDuration doesn't stop on disconnection

### ISSUE THREAD

**Issue by AsafMag** [danikf/tik4net#41]
The following code:

```csharp
var cmd = connection.CreateCommand("interface/wireless/sniffer/sniff")
cmd.AddParameter("interface", "wlan1");
cmd.ExecuteListWithDuration(9999);
```

Doesn't stop when I shut down my MikroTik board. A breakpoint inside `ExecuteListWithDuration` shows that `Connection._isOpened == true`.

I haven't tested other functions such as `ExecuteAsync` etc.

**Comment by danikf** [comment]
Hi,
and what behavior do you expect? Exception?
D

**Comment by AsafMag** [comment]
@danikf This doesn't seem to work even after the updates you uploaded yesterday: I launched a command for 9999 seconds and disabled the ethernet interface on the PC. `Connection.IsConnected` was then set to `false` but `ExecuteListWithDuration` was still running.

**Comment by AsafMag** [comment]
It returns immediately.
There are other problem now:
1. How can I know if it returned due to disconnection or duration?
2. `IsRunning` stays `true` (kind of answers the first problem but I believe it shouldn't be like that).

**Comment by danikf** [comment]
Hi,
finally I have implemented both scenarios (overloads with exception and also second overload with returning incomplete response with error info).

In hope it solved your case,
D
PS: I would still recommend to use
1) Single connection + multiple ExecuteAsync calls
2) Multiple connections + single sync call

**Comment by AsafMag** [comment]
@danikf Looking good, thanks :)
