### ISSUE TITLE
[Request] Sub Exceptions of TikCommandException

### ISSUE THREAD

**Issue by Deantwo** [danikf/tik4net#50]
I would love to see some special error cases moved into sub exceptions of `TikCommandException`.

For example login attempts could get its own sub exception.
So code like this would be easier to detect error types without reading the exception text.
``` C#
try
{
    using (ITikConnection connection = ConnectionFactory.OpenConnection(TikConnectionType.Api, host, user.UserName, user.Password))
    {
        ...
    }
}
catch (System.Net.Sockets.SocketException)
{
    // The socket could not conenct.
    throw;
}
catch (tik4net.TikCommandException)
{
    // Login failed.
    // Command failed.
    // Some other Tik4Net error.
    throw;
}
```
For example if you added a `TikLoginException`, we could do:
``` C#
try
{
    using (ITikConnection connection = ConnectionFactory.OpenConnection(TikConnectionType.Api, host, user.UserName, user.Password))
    {
        ...
    }
}
catch (System.Net.Sockets.SocketException)
{
    // The socket could not conenct.
    throw;
}
catch (tik4net.TikLoginException)
{
    // Login failed.
    throw;
}
catch (tik4net.TikCommandException)
{
    // Command failed.
    // Some other Tik4Net error.
    throw;
}
```
If you make in inherit from `TikCommandException`, it would supposedly not be a breaking change.

But if you don't mind a breaking change, for example for the next major update, you could go further and make a new root exception just called `TikException`, and make all other Tik3Net exceptions inherit from that.
And you could even wrap the `System.Net.Sockets.SocketException` from the socket in the `TikConnectionException`. But I don't know what best practice is for wrapping system exceptions.

**Comment by danikf** [comment]
Hi,
agreed ... (I was just lazy to do it, but you are 100% right).
D

**Comment by danikf** [comment]
Hopefully fully covered by previous commits.
