### ISSUE TITLE
generate multiple hotspot user and show current TX and RX Rate

### ISSUE THREAD

**Issue by meizoel** [danikf/tik4net#55]
i wanna ask something , i have create an android application using this tools
here's the playstore link https://play.google.com/store/apps/details?id=com.meizoel.imikrotik

first question is how i can generate 20 user hotspot with random username and password
if have try two scenario using connection.save();
scenario one without sleep threed , i only create 5 user.
scenario two with sleep thread it up to 10 user , doesn't meet my requirment for create 20 user.
log message from both scenario are connection timeout, how to make it fill the requirment..

and second question how to show current TX Rate and RX Rate on list interface, hotspot active user and host

please help me

**Comment by danikf** [comment]
Question, not issue.
