### ISSUE TITLE
[Suggestion] ExecuteScalarOrDefault

### ISSUE THREAD

**Issue by Deantwo** [danikf/tik4net#59]
Same as with #58, `cmd.ExecuteScalar()` throws an exception when no result is found. It might be acceptable that it throws an exception when there are multiple results, rather than randomly return the first value in the sentence.

But a `cmd.ExecuteScalarOrDefault()` would be nice to have.

**Comment by Deantwo** [comment]
Could actually upgrade `cmd.ExecuteScalar()` to take a string argument, so it can automatically add a command parameter with `$"=.proplist={target}"`.

**Comment by Deantwo** [comment]
Another fun idea, do a scalar list.
Extension method example:
``` C#
internal static List<string> ExecuteScalarList(this ITikCommand cmd)
{
    //throw new NotImplementedException();
    IEnumerable<ITikReSentence> listRe = cmd.ExecuteList();
    List<string> listScalar = new List<string>();
    foreach (ITikReSentence re in listRe)
    {
        string scalar = re.Words.Single().Value;
        listScalar.Add(scalar);
    }
    return listScalar;
}

internal static List<string> ExecuteScalarList(this ITikCommand cmd, string target)
{
    cmd.AddProplistParameter(target);
    //throw new NotImplementedException();
    IEnumerable<ITikReSentence> listRe = cmd.ExecuteList();
    return cmd.ExecuteScalarList();
}
```
This might be a little too stuerational, but useful none the less.

**Comment by danikf** [comment]
ExecuteScalarOrDefault - implemented
ExecuteScalar + target - implemented
ExecuteScalarList - implemented as ExecuteList(params string[] proplistFields)
