### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by niphone** [danikf/tik4net#60]
I call the SSID field in the CapsManRegistrationTable through the API. Since the SSID contains Chinese characters, the displayed SSID result has an unrecognized question mark.

connection.Encoding = Encoding.GetEncoding("windows-1250");

Use connection.Encoding = Encoding.GetEncoding("windows-1250"); An error message appears: System.ArgumentException: 'windows-1250' is not a supported encoding name. For information on defining a custom encoding

Thank you so much!

**Comment by danikf** [comment]
Hi,
use Chinese encoding and not easter europe encoding (windows1250).
D


po 14. led 2019 2:25 odesílatel niphone <notifications@github.com> napsal:

**Comment by niphone** [comment]
connection.Encoding = Encoding.GetEncoding("utf-8");
Still not, the characters displayed are still question marks.

**Comment by danikf** [comment]
Hi,
Utf8 is not good idea. You must use your real encoding (and test it via
winbox before - not sure if chinese works with mikrotik at all).
D
