### ISSUE TITLE
Problem with connection - Can not read sentence from connection

### ISSUE THREAD

**Issue by siasty** [danikf/tik4net#61]
Hi,
I have a case trying to use your api in dotnet core 2.2 
I have a connection error  **Can not read sentence from connection**
the case is random and I do not know how to protect it. 
Did you have such cases or you can give me some hints?

Best regards
Maciej

**Comment by danikf** [comment]
I would recommend to create new connection for every mikrotik session (do leave open connection for long time) + use connection in using(....) block to be sure it will be closed.

Does it help?
D

**Comment by danikf** [comment]
Closed - no response.

**Comment by TheTrigger** [comment]
Hello, same issue here

**RouterOS Version**: `4.48.3` on `RB951Ui` and `CHR`
**Tik4Net Version**: `3.5.0`
**.NET Version**: `5.0`

Single connection, no other clients connected

```csharp
private static async Task Main(string[] args)
{
    using var connection = ConnectionFactory.CreateConnection(TikConnectionType.Api);

    connection.OnReadRow += Connection_OnReadRow;
    connection.OnWriteRow += Connection_OnWriteRow;

    connection.Open("192.168.1.253", 8291, "admin", "");
}
```

### Output

```
/login
=name=admin
=password=
```

### Exception

```
System.IO.IOException: 'Can not read sentence from connection'
```
