### ISSUE TITLE
New API Login method needs documentation

### ISSUE THREAD

**Issue by RavenWing71** [danikf/tik4net#64]
With RouterOS v6.45 out now, please document the change to Api_V2.  If no where else, then here: https://github.com/danikf/tik4net/wiki/CRUD-examples-for-all-APIs.  But a note on the Wiki front page would help those of us who already have working code that works no more.

**Comment by raminrajabi** [comment]
With New Release (6.45.6) I can't log in to MikroTik via API. the new API protocol is needed.

**Comment by hkusulja** [comment]
Also here same problem. Can not login using API and this NuGet after RouterOS update...

**Comment by tomidix** [comment]
Can someone write how we should connect now? ApiSsl, ApiSsl_v2? Is it still possible to connect by username and password?

**Comment by danikf** [comment]
ConnectionFactory.CreateConnection(TikConnectionType.Api_v2) is your friend ;-)

... will update WIKi soon ...

D

**Comment by tomidix** [comment]
@danikf Thanks for the fast reply.
I tried TikConnectionType.Api_v2 already prior to writing here. The result is the same: '_invalid user name or password (6)_'.
`using (ITikConnection connection = ConnectionFactory.OpenConnection(TikConnectionType.Api_v2, mikrotikGateway.Server, mikrotikGateway.Port, mikrotikGateway.Username, mikrotikGateway.Password))`
User can login to winbox though.
Are there any requirements special from the router side for this to work?

**Comment by raminrajabi** [comment]
I used the api_v2 and worked for me on Mikrotik 6.45.6

**Comment by raminrajabi** [comment]
ITikConnection connection;

      connection = ConnectionFactory.CreateConnection(TikConnectionType.Api_v2);
                connection.ReceiveTimeout = 5000;
                connection.SendTimeout = 5000;
                connection.Open(txtIP.Text, txtUsername.Text, txtPassword.Text);

                this.Text = Title + " - " + connection.ExecuteScalar("/system/identity/print");

**Comment by tomidix** [comment]
@raminrajabi thanks for the example. Unfortunately the result is the same as before.
I even tried creating new user with full rights on router, still the same problem.
RouterOs version is 6.45.6 too.

**Comment by danikf** [comment]
Is API allowed in mikrotik configuration?
What about encoding? (exotic characters in username / password)

**Comment by tomidix** [comment]
In the mikrotik log there are records like this: _login failure for user 'X' from 'IP' via api_
I also checked if api is enabled, firewall etc. so answers would be:
Yes
Yes
Yes
only English characters are present in username/password, no encoding is set and needed
Yes

**Comment by danikf** [comment]
Strange :/
last guess: Any ip subnet limitation on user or api service?

**Comment by tomidix** [comment]
Nope, no subnet limitations both on user and api service.
Tried on another Mikrotik (test device) and this works like you've said.
Before the RouterOs update it worked with both api and api_v2.. after the update on test device it doesn't work with api and it works ok with api_v2 TikConnectionType..
Strange but it is way it is.. 
Thanks for your help.

**Comment by hkusulja** [comment]
@tomidix it magically started working, so this is closed, right?

**Comment by danikf** [comment]
New version of login (back api and api_ssl) will work for both old and new version of mikrotik.
