### ISSUE TITLE
how to use "find" filter without using ".id" in set command ?

### ISSUE THREAD

**Issue by bi9595** [danikf/tik4net#66]
Hi danikf,
please help me about:
how to use "find" filter without using ".id" in set command ?
for exmple:
1- interface set [ find name=ether1 ] comment=abcd
2- interface set ether1 comment=34343434

Is possible above commands in tik4net?

Regards

**Comment by saputra19** [comment]
how about this
Dim cmd As ITikCommand = connection.CreateCommandAndParameters("/interface/set", "name", "ifaceName", "comment", ifaceComment)
                cmd.ExecuteNonQuery()

**Comment by danikf** [comment]
Mikrotik API generic issue, not tik4net specific. Solution mentioned on support forum.
