### ISSUE TITLE
/interface/lte/info - no such item (4)

### ISSUE THREAD

**Issue by iDeedz** [danikf/tik4net#68]
Hi,

I've started playing with this library and have found that I am unable to retrieve the LTE info from the router.

I am using the following code to try and get information.

_Dim connection = ConnectionFactory.OpenConnection(TikConnectionType.Api, IP, u, p)
Dim loadCmd = connection.CreateCommandAndParameters("/interface/lte/info", "number", "0", "once", "")
Dim response = loadCmd.ExecuteList()_

We have a working version for php to get the LTE info, but this will have to be ported to a vb.net application.

Not sure if I am doing something wrong, or perhaps something else I am missing?

**Comment by danikf** [comment]
Take a look into debug window - you will see what API command is executed. Than use parameters in correct format. I would expect that "number" and "once" are different types of parameters.

D

**Comment by iDeedz** [comment]
Thank you @danikf 

Will try again once I have a device to test with.
