### ISSUE TITLE
Number system of the ID field

### ISSUE THREAD

**Issue by Shepard199** [danikf/tik4net#71]
Hello, please tell me in which numeral system the Id field is obtained?, for example, on microtic the record has the ordinal number 957, and tik4net displays it as *CC7D9

**Comment by danikf** [comment]
Hello, I am not sure if there is any correlation between ids and ordinal numbers. Probably not (I would expect, that API IDs are counted from 1 but the sequence is not decreased when item is deleted). 

API ID is just ID :-) If you want to find exact item, use serach via coment or name or another key. In some cases names could also be used via API as primary search criteria. 

D
