### ISSUE TITLE
ExecuteScalarOrDefault Throws Exceptions

### ISSUE THREAD

**Issue by Deantwo** [danikf/tik4net#74]
I think you might have misunderstood the normal behavior of "OrDefault" methods in C#.

Normally a "OrDefult" method returns `null` when the non-"OrDefault" version of the method would through an exception. Well it would throw the `default(T)` of whatever the return type is, which for a `string` is `null`.

I am not completely sure what your version of "OrDefault" methods are supposed to do.

https://github.com/danikf/tik4net/blob/583c41e1a5fa829ea90434a186df140fb66ecd1f/tik4net/Api/ApiCommand.cs#L290
https://github.com/danikf/tik4net/blob/583c41e1a5fa829ea90434a186df140fb66ecd1f/tik4net/Api/ApiCommand.cs#L295
https://github.com/danikf/tik4net/blob/583c41e1a5fa829ea90434a186df140fb66ecd1f/tik4net/Api/ApiCommand.cs#L300

**Comment by Deantwo** [comment]
I will confess that I had you implement these "OrDefault" methods, but I hadn't had the chance to test them before recently.

**Comment by danikf** [comment]
Hi Deantwo,

could you please close this issue or explain the problem. I agree with your description, but I believe that the behavior is as described :-)

Thx,
D

**Comment by Deantwo** [comment]
Main issue is, as the title says, the methods throw an exception.
https://github.com/danikf/tik4net/blob/583c41e1a5fa829ea90434a186df140fb66ecd1f/tik4net/Api/ApiCommand.cs#L336

And also that the `string defaultValue` parameter seems pointless and a little confusing. It would be simpler to just always return `null` if the command resulted in more than one or no values. Like a normal `SingleOrDefault` method.
